L /opt/Vesktop - - - - ../usr/lib/vesktop/opt/Vesktop
L /usr/share/applications/vesktop.desktop - - - - ../usr/lib/vesktop/share/applications/vesktop.desktop
L /usr/share/icons/hicolor/scalable/apps/vesktop.svg - - - - ../usr/lib/vesktop/share/icons/hicolor/scalable/apps/vesktop.svg
